# Air config for running cryptool daemon with hot-reload
# Docs: https://github.com/cosmtrek/air

root = "./"
tmp_dir = "tmp"

[build]
# Build the binary into tmp/
cmd = "go build -o ./tmp/cryptool ."
bin = "./tmp/cryptool"
# Command to run after build
full_bin = "./tmp/cryptool daemon 40000"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go$"]
delay = 1000 # ms
stop_on_error = true

[log]
color = true

[misc]
clean_on_exit = true
