package strategy

import (
	"time"
)

// Signal represents a trading signal (BUY, SELL, or HOLD)
type Signal int

const (
	SignalHold Signal = iota
	SignalBuy
	SignalSell
)

// StrategyConfig holds configuration for a specific strategy
type StrategyConfig struct {
	ID                string                 `json:"id"`
	Name              string                 `json:"name"`
	Description       string                 `json:"description"`
	Indicators        map[string]interface{} `json:"indicators"`
	SignalCombination string                 `json:"signal_combination"` // AND, OR, WEIGHTED
}

// StrategySignal represents a signal generated by a single indicator
type StrategySignal struct {
	IndicatorName string    `json:"indicator_name"`
	Signal        Signal    `json:"signal"`
	Confidence    float64   `json:"confidence"` // 0.0 to 1.0
	Timestamp     time.Time `json:"timestamp"`
}

// CombinedSignal represents the result of combining multiple indicator signals
type CombinedSignal struct {
	StrategyID      string            `json:"strategy_id"`
	FinalSignal     Signal            `json:"final_signal"`
	Confidence      float64           `json:"confidence"`
	IndividualSignals []StrategySignal `json:"individual_signals"`
	Timestamp       time.Time         `json:"timestamp"`
}

// BacktestResult contains metrics for a single backtest run
type BacktestResult struct {
	StrategyID          string            `json:"strategy_id"`
	StrategyName        string            `json:"strategy_name"`
	StartTime           time.Time         `json:"start_time"`
	EndTime             time.Time         `json:"end_time"`
	TotalTrades         int               `json:"total_trades"`
	WinningTrades       int               `json:"winning_trades"`
	LosingTrades        int               `json:"losing_trades"`
	WinRate             float64           `json:"win_rate"` // percentage
	TotalReturn         float64           `json:"total_return"` // percentage
	AnnualizedReturn    float64           `json:"annualized_return"` // percentage
	MaxDrawdown         float64           `json:"max_drawdown"` // percentage
	SharpeRatio         float64           `json:"sharpe_ratio"`
	ProfitFactor        float64           `json:"profit_factor"` // gross profit / gross loss
	AvgWinSize          float64           `json:"avg_win_size"`
	AvgLossSize         float64           `json:"avg_loss_size"`
	LargestWin          float64           `json:"largest_win"`
	LargestLoss         float64           `json:"largest_loss"`
	ConsecutiveWins     int               `json:"consecutive_wins"`
	ConsecutiveLosses   int               `json:"consecutive_losses"`
}

// Trade represents a single trade executed during backtesting
type Trade struct {
	ID            string    `json:"id"`
	EntryTime     time.Time `json:"entry_time"`
	EntryPrice    float64   `json:"entry_price"`
	ExitTime      time.Time `json:"exit_time"`
	ExitPrice     float64   `json:"exit_price"`
	Quantity      float64   `json:"quantity"`
	PnL           float64   `json:"pnl"` // profit/loss in absolute terms
	PnLPercent    float64   `json:"pnl_percent"` // profit/loss in percentage
	Type          string    `json:"type"` // LONG or SHORT
	StrategyID    string    `json:"strategy_id"`
}