-- +goose Up
ALTER TABLE products
    ADD COLUMN price DOUBLE PRECISION,
    ADD COLUMN price_percentage_change_24h DOUBLE PRECISION,
    ADD COLUMN volume_24h DOUBLE PRECISION,
    ADD COLUMN volume_percentage_change_24h DOUBLE PRECISION,
    ADD COLUMN base_increment DOUBLE PRECISION,
    ADD COLUMN quote_increment DOUBLE PRECISION,
    ADD COLUMN quote_min_size DOUBLE PRECISION,
    ADD COLUMN quote_max_size DOUBLE PRECISION,
    ADD COLUMN base_min_size DOUBLE PRECISION,
    ADD COLUMN base_max_size DOUBLE PRECISION,
    ADD COLUMN watched BOOLEAN,
    ADD COLUMN is_new BOOLEAN,
    ADD COLUMN status TEXT,
    ADD COLUMN cancel_only BOOLEAN,
    ADD COLUMN limit_only BOOLEAN,
    ADD COLUMN post_only BOOLEAN,
    ADD COLUMN trading_disabled BOOLEAN,
    ADD COLUMN auction_mode BOOLEAN,
    ADD COLUMN product_type TEXT,
    ADD COLUMN quote_currency_id TEXT,
    ADD COLUMN base_currency_id TEXT,
    ADD COLUMN fcm_trading_session_details JSONB,
    ADD COLUMN mid_market_price DOUBLE PRECISION,
    ADD COLUMN alias TEXT,
    ADD COLUMN alias_to TEXT[],
    ADD COLUMN base_display_symbol TEXT,
    ADD COLUMN quote_display_symbol TEXT,
    ADD COLUMN view_only BOOLEAN,
    ADD COLUMN price_increment DOUBLE PRECISION,
    ADD COLUMN display_name TEXT,
    ADD COLUMN product_venue TEXT,
    ADD COLUMN approximate_quote_24h_volume DOUBLE PRECISION,
    ADD COLUMN new_at TIMESTAMPTZ,
    ADD COLUMN future_product_details JSONB;

-- +goose Down
ALTER TABLE products
    DROP COLUMN price,
    DROP COLUMN price_percentage_change_24h,
    DROP COLUMN volume_24h,
    DROP COLUMN volume_percentage_change_24h,
    DROP COLUMN base_increment,
    DROP COLUMN quote_increment,
    DROP COLUMN quote_min_size,
    DROP COLUMN quote_max_size,
    DROP COLUMN base_min_size,
    DROP COLUMN base_max_size,
    DROP COLUMN watched,
    DROP COLUMN is_new,
    DROP COLUMN status,
    DROP COLUMN cancel_only,
    DROP COLUMN limit_only,
    DROP COLUMN post_only,
    DROP COLUMN trading_disabled,
    DROP COLUMN auction_mode,
    DROP COLUMN product_type,
    DROP COLUMN quote_currency_id,
    DROP COLUMN base_currency_id,
    DROP COLUMN fcm_trading_session_details,
    DROP COLUMN mid_market_price,
    DROP COLUMN alias,
    DROP COLUMN alias_to,
    DROP COLUMN base_display_symbol,
    DROP COLUMN quote_display_symbol,
    DROP COLUMN view_only,
    DROP COLUMN price_increment,
    DROP COLUMN display_name,
    DROP COLUMN product_venue,
    DROP COLUMN approximate_quote_24h_volume,
    DROP COLUMN new_at,
    DROP COLUMN future_product_details;
